CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    login character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(30) NOT NULL,
    attempts integer DEFAULT 0,
    blocked boolean DEFAULT FALSE,
    PRIMARY KEY (id),
    CONSTRAINT login UNIQUE (login)
);

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;


INSERT INTO users (login, password, role)
VALUES ('admin', 'scrypt:32768:8:1$m78swKwIJ0OoLUOo$e8e83aa96d0796fac739e2cf8df8e5ea96223cdbf06442e2f41f5a743d7c773801a561b69b2cd2e38c67dca500ca7a34b203b30548f13b1e6da9142dec64b93c', 'Администратор'); -- 1234

INSERT INTO users (login, password, role)
VALUES ('student', 'scrypt:32768:8:1$m78swKwIJ0OoLUOo$e8e83aa96d0796fac739e2cf8df8e5ea96223cdbf06442e2f41f5a743d7c773801a561b69b2cd2e38c67dca500ca7a34b203b30548f13b1e6da9142dec64b93c', 'Пользователь'); -- 1234