CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    login character varying(100) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT login UNIQUE (login)
);


CREATE TABLE public.notes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    id_user integer REFERENCES users(id) NOT NULL,
    created_at DATE NOT NULL,
    PRIMARY KEY (id)
);


INSERT INTO users (login)
VALUES 
('meow2'),
('sepw'),
('keow'),
('deow22')

INSERT INTO notes (title, content, id_user, created_at)
VALUES
('meow2', 'slp', 3, '1992.10.11'),
('meow3', 'dadasd13123123', 2, '1992.10.10'),
('meow1', 'dadasd13123123', 1, '1992.10.12')


